import { Inter } from "next/font/google";
import "./globals.css";
import "./ant_design.css";
import Navbar from "@/components/shared/Navbar";

// Import the Inter font (if needed for other parts of the project)
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Soft Shift",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
  <link
    href="https://fonts.googleapis.com/css2?family=Lexend+Giga:wght@100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet"
        />
 <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
