/* eslint-disable @next/next/no-page-custom-font */
import "./globals.css";
import "./ant_design.css";
import { ToastContainer } from "react-toastify";
import ScrollToTop from "@/components/shared/ScrollToTop";
import { Urbanist } from "next/font/google";


export const metadata = {
  title: "Soft Shift",
  description: "Generated by create next app",
};

const urbanist = Urbanist({ subsets: ["latin"], weight: ["100", "400", "700"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link
            href="https://fonts.googleapis.com/css2?family=Lexend+Giga:wght@100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
                />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body className={`${urbanist.className} overflow-x-hidden`}>
        {children}
        <ToastContainer />
        <ScrollToTop />
      </body>
    </html>
  );
}
